### ISSUE TITLE
pathing problem

### ISSUE THREAD

**Issue by ghost** [luboslenco/kha3d_examples#1]
I have the kha3d git cloned to local, and i want to git clone the tutorial code into my local kha3D/src folder.

I could do it but them i will corrupt the kha3d for next time.

So i was wondering if there will be a way of having a src workspace local folder that exists outside the source of the kha3d. I can image the way to do this is with a bash profile ?

**Comment by ghost** [comment]
a related issue.
I just copied all the tutorials into the main Soures folder.
The 'node Kha/make -t html5# now fails.
Not sure what to do..
Here is the folder structure below as a tree.

gedw99-MacBook-Pro:Sources apple$ tree
.
├── Empty.hx
├── Main.hx
└── kha3d_examples
    ├── README.md
    ├── tutorial01
    │   ├── Sources
    │   │   ├── Empty.hx
    │   │   └── Main.hx
    │   └── project.kha
    ├── tutorial02
    │   ├── Sources
    │   │   ├── Empty.hx
    │   │   ├── Main.hx
    │   │   └── Shaders
    │   │       ├── simple.frag.glsl
    │   │       └── simple.vert.glsl
    │   └── project.kha
    ├── tutorial03
    │   ├── Sources
    │   │   ├── Empty.hx
    │   │   ├── Main.hx
    │   │   └── Shaders
    │   │       ├── simple.frag.glsl
    │   │       └── simple.vert.glsl
    │   └── project.kha
    ├── tutorial04
    │   ├── Sources
    │   │   ├── Empty.hx
    │   │   ├── Main.hx
    │   │   └── Shaders
    │   │       ├── simple.frag.glsl
    │   │       └── simple.vert.glsl
    │   └── project.kha
    ├── tutorial05
    │   ├── Assets
    │   │   └── uvtemplate.png
    │   ├── Sources
    │   │   ├── Empty.hx
    │   │   ├── Main.hx
    │   │   └── Shaders
    │   │       ├── simple.frag.glsl
    │   │       └── simple.vert.glsl
    │   └── project.kha
    ├── tutorial06
    │   ├── Assets
    │   │   └── uvtemplate.png
    │   ├── Sources
    │   │   ├── Empty.hx
    │   │   ├── Main.hx
    │   │   └── Shaders
    │   │       ├── simple.frag.glsl
    │   │       └── simple.vert.glsl
    │   └── project.kha
    ├── tutorial07
    │   ├── Assets
    │   │   ├── cube.obj
    │   │   └── uvmap.png
    │   ├── Sources
    │   │   ├── Empty.hx
    │   │   ├── Main.hx
    │   │   ├── ObjLoader.hx
    │   │   └── Shaders
    │   │       ├── simple.frag.glsl
    │   │       └── simple.vert.glsl
    │   └── project.kha
    └── tutorial08
        ├── Assets
        │   ├── suzanne.obj
        │   └── uvmap.png
        ├── Sources
        │   ├── Empty.hx
        │   ├── Main.hx
        │   ├── ObjLoader.hx
        │   └── Shaders
        │       ├── simple.frag.glsl
        │       └── simple.vert.glsl
        └── project.kha

**Comment by luboslenco** [comment]
Hi, you can now use Kha with haxelib:
http://tech.ktxsoftware.com/kha-on-haxelib/

Does this help?

**Comment by luboslenco** [comment]
It is now also possible to use Kha externally, and call 'node path/to/Kha/make', hope that helps.

**Comment by joeblew99** [comment]
Hmm not really.
I use golang server side, and polymer client side.

Have not dabbled with haxe
