### ISSUE TITLE
IDE gets total screen size from multiple monitors

### ISSUE THREAD

**Issue by jpryne** [luboslenco/kha3d_examples#9]
I'm on a system with an Oculus Rift as well as a main monitor. The IDE  is doubled in scale, making it unusable.
![ss](https://user-images.githubusercontent.com/1497564/52969609-d16ff680-3365-11e9-9215-86595103ae03.png)

**Comment by luboslenco** [comment]
Sorry for not resolving this, it looks like this is an issue with KodeGarden. If you are still around it may be worth to open at:
https://github.com/Kode/KodeGarden/issues

**Comment by jpryne** [comment]
Will do, thanks.
